name: Reusable Pull Image Workflow

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      pull-image:
        required: true
        type: boolean
        default: false
      image-tag:
        required: false
        type: string
        default: latest

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.pull-image }}
    steps:
      - name: Pull Docker image
        run: docker pull ${{ inputs.image-name }}:${{ inputs.image-tag }}
