name: Reusable Pull Image Workflow

# Every caller which call this - will use this commands with its repository. Meaning this is just a template.
# Instead of writing the bellow commands over and over again, this can be reused. 
# it actions/checkout is made - it will download the repository of the caller workflow. 
# this repository - even if it has files in it - it won't be seen in the caller workflow, they can't be used.

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      pull-image:
        required: true
        type: boolean
        default: false
      image-tag:
        required: false
        type: string
        default: latest

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: get the repo
        uses: actions/checkout@v3
      - name: make .tar files
        run: |
          tar -cvf ${{ github.sha }}-file1.tar for-upload-1.txt
          tar -cvf ${{ github.sha }}-file2.tar for-upload-2.txt
      - name: upload tar files
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            ${{ github.sha }}-file1.tar
            ${{ github.sha }}-file2.tar
          retention-days: 1
  download-artifacts:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    steps:
      - name: Download tar files
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Extract tar files
        run: |
          tar -xvf ${{ github.sha }}-file1.tar
          tar -xvf ${{ github.sha }}-file2.tar
      - name: Read the files and delete
        run: |
          cat for-upload-1.txt
          cat for-upload-2.txt
          ls
          rm ${{ github.sha }}-file1.tar ${{ github.sha }}-file2.tar for-upload-1.txt for-upload-2.txt
          ls

  pull-docker-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.pull-image }}
    steps:
      - name: Pull Docker image
        run: docker pull ${{ inputs.image-name }}:${{ inputs.image-tag }}
