name: Reusable Pull Image Workflow

# Every caller which call this - will use this commands with its repository. Meaning this is just a template.
# Instead of writing the bellow commands over and over again, this can be reused. 
# if actions/checkout is made - it will download the repository of the caller workflow, not this repository! 
# this repository - even if it has files in it - they won't be seen in the caller workflow.

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      pull-image:
        required: true
        type: boolean
        default: false
      image-tag:
        required: false
        type: string
        default: latest

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: get the repo
        uses: actions/checkout@v3
      - name: make .tar files
        run: |
          tar -cvf ${{ github.sha }}-file3.tar for-upload-3.txt
      - name: upload tar files
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            ./tools/files
          retention-days: 1
      - name: second upload of files
        uses: actions/upload-artifact@v3
        with:
          name: my-second-artifact
          path: |
            ${{ github.sha }}-file3.tar
          retention-days: 1
  download-artifacts:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    steps:
      - name: Download tar files
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ./download
      - name: Read the files and delete
        run: |
          ls ./download
          cat ./download/for-upload-1.txt
          cat ./download/for-upload-2.txt
          ls
          rm ./download/for-upload-1.txt ./download/for-upload-2.txt
          ls

  download-second-artifacts:

    runs-on: ubuntu-latest
    needs: [upload-artifacts, download-artifacts]
    steps:
      - name: Download tar files
        uses: actions/download-artifact@v3
        with:
          name: my-second-artifact
      - name: Extract tar files
        run: |
          tar -xvf ${{ github.sha }}-file3.tar
      - name: Read the files and delete
        run: |
          cat for-upload-3.txt
          rm ${{ github.sha }}-file3.tar for-upload-3.txt

  pull-docker-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.pull-image }}
    steps:
      - name: Pull Docker image
        run: docker pull ${{ inputs.image-name }}:${{ inputs.image-tag }}
